GO_LDFLAGS := -X main.Tag=$(shell git describe --exact-match --tags 2>/dev/null) \
              -X main.Commit=$(shell git rev-parse HEAD 2>/dev/null) \
              -X "main.BuildTime=$(shell date -Iseconds)"

# goolm selects mautrix's pure-Go Olm implementation. Without it the build needs
# libolm's C headers, which is an avoidable dependency for this bridge.
GO_TAGS := goolm

.PHONY: all build test cover lint fmt example-config clean \
        dev-up dev-down dev-bridge dev-logs dev-reset

DEV_COMPOSE := docker compose -f docker-compose.dev.yaml

all: build

build:
	go build -tags '$(GO_TAGS)' -ldflags '$(GO_LDFLAGS)' -o matrix-nctalk ./cmd/matrix-nctalk

test:
	go test -tags '$(GO_TAGS)' -race ./...

# The project holds itself to 85% statement coverage.
COVERAGE_MIN := 85

cover:
	go test -tags '$(GO_TAGS)' -coverprofile=coverage.out ./...
	@go tool cover -func=coverage.out | tail -1
	@pct=$$(go tool cover -func=coverage.out | tail -1 | grep -oE '[0-9]+\.[0-9]+'); \
	  awk -v p="$$pct" -v m="$(COVERAGE_MIN)" 'BEGIN { if (p+0 < m+0) { printf "coverage %.1f%% is below the %d%% minimum\n", p, m; exit 1 } printf "coverage %.1f%% meets the %d%% minimum\n", p, m }'

lint:
	go vet -tags '$(GO_TAGS)' ./...
	gofmt -l pkg cmd

fmt:
	gofmt -w pkg cmd

# The bridge refuses to overwrite an existing example config, so this removes it
# first — otherwise the target silently does nothing and the committed example
# drifts behind the code, which is worse than not having one.
example-config: build
	rm -f example-config.yaml
	./matrix-nctalk -e -c example-config.yaml

clean:
	rm -f matrix-nctalk coverage.out

# --- Local development stack -------------------------------------------------
# Nextcloud + Talk + Synapse in Docker, with the bridge itself running on the
# host. See README.md and docker-compose.dev.yaml.

# Bring the whole stack up and configure it. Safe to re-run.
dev-up:
	./dev/up.sh

# Run the bridge against the dev stack in the foreground.
dev-bridge: build
	./matrix-nctalk -c dev/config.yaml

dev-logs:
	$(DEV_COMPOSE) logs -f

# Stop the containers but keep all data.
dev-down:
	$(DEV_COMPOSE) down

# Destroy the stack and every trace of its state: Nextcloud files and database,
# Synapse's database and signing key, and the bridge's config and database.
# Everything here is regenerated by dev-up, but nothing is recoverable.
dev-reset:
	@printf 'This deletes all dev stack data (Nextcloud, Synapse and bridge databases). Type "yes" to continue: '; \
	  read -r reply; [ "$$reply" = yes ] || { echo "Aborted."; exit 1; }
	$(DEV_COMPOSE) down -v
	rm -rf dev/synapse dev/config.yaml dev/matrix-nctalk.db dev/matrix-nctalk.db-shm dev/matrix-nctalk.db-wal
	@echo "Dev stack reset. Run 'make dev-up' to rebuild it."
